name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./pixel-towers-master
    - name: Build with Gradle
      run: ./gradlew assembleDebug #build#
      working-directory: ./pixel-towers-master
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: '**/*.apk'
